network:
  img_model: resnet50
  text_model: bert
  free_layers: 12 # set 12 to freeze all layers in bert
  text_model_arch: general # specialized/general
  feature_dim: 768

  projection_head:
    mlp_hidden_size: 2048
    projection_size: 768

img_path: 'your npy' # add your image file path here, we compress all image to one npy file
text_path: 'your csv' # add your text file path here


trainer:
  batch_size: 128
  test_batch_size: 200
  checkpoint_interval: 100000
  max_epochs: 20
  lr: 2.0e-4
  num_workers: 8
  test_interval: 2
  loss: 'CICL'
  smooth: 'exp'
  ratio: 0.2

optimizer:
  params:
    lr: 2.0e-4
    weight_decay: 5.0e-2

wandb_name: 'imitate_cicl'
